nordic-institute/X-Road-Security-Server-sidecar

README.md, setup_security_server_sidecar.sh, sidecar/files/ss-entrypoint.sh
- Make autologin pin code readable by xroad user.
- Minor optimisations in the initial configuration script.
=> XRDDEV-788

README.md, setup_security_server_sidecar.sh, sidecar/Dockerfile
- Added custom username and password for the Admin UI login.
=> XRDDEV-787

README.md, sidecar/Dockerfile, sidecar/files/ss-entrypoint.sh
Added generation of internal ssl certificates on the initial docker configuration script.
=> XRDDEV-678

README.md, sidecar/Dockerfile, sidecar/files/ss-entrypoint.sh
- Added upgrade logic to initial docker configuration script.
- Added version output on image docker build file.
- Updated README.md with description of the new feature.
=> XRDDEV-789

setup_security_server_sidecar.sh, sidecar/Dockerfile, sidecar/files/autologin.conf, sidecar/files/custom-fetch-pin.sh, sidecar/files/ss-entrypoint.sh
- Added logic to configure autologin custom-fetch-pin.sh script.
- Added nginx configuration to expose web service to serve on /autologin and port 5555 the user-supplied PIN code for the autologin script.
- Removed autologin PIN code configuration step in entrypoint script.
=> XRDDEV-901

README.md, setup_security_server_sidecar.sh, sidecar/Dockerfile, sidecar/files/ss-entrypoint.sh
Added postgresql instructions to change default serverconf credentials in the initial docker build.
Added amendment of db.properties and pg_hba.conf files.
Updated README.md with description of new feature.
=> XRDDEV-786

README.md
Updated README.md with the installation and initial configuration steps and current limitations.
=> XRDDEV-902

README.md, setup_security_server_sidecar.sh, sidecar/files/ss-entrypoint.sh
- Added logic to configure remote database in the first run. Updated setup script with the new required arguments and instructions. Added arguments validation.
- Updated README.md with the installation steps and initial configuration steps for the remote database server.
=> XRDDEV-986

README.md, setup_security_server_sidecar.sh, sidecar/files/ss-entrypoint.sh
Add volume support for xroad config
https://jira.niis.org/browse/XRDDEV-984?filter=-1
=> XRDDEV-984 

README.md
Add information in readme about the testing of the external database in aws
=> XRDDEV-1062 

README.md, sidecar/Dockerfile, sidecar/files/provider-entrypoint.sh, sidecar/files/provider-ss-xroad.conf, sidecar/files/ss-xroad.conf, sidecar/provider/Dockerfile
Environmental and operational monitoring
=> XRDDEV-994

setup_security_server_sidecar.sh, sidecar/Dockerfile, sidecar/files/provider-entrypoint.sh, sidecar/files/ss-entrypoint.sh
- Added bind mount for xroad.properties file.
- Removed references to XROAD_DB_PASSWORD environment variable and code storing the password in entrypoint scripts (vanilla and provider).
=> XRDDEV-1037

README.md
I want to test how long it takes to setup Sidecar from scratch so that I know how to communicate expectations to customers
=> XRDDEV-1086 

README.md, doc/kubernetes_security_guide.md, doc/kubernetes_security_server_sidecar_user_guide.md, doc/security_server_sidecar_user_guide.md
Added clarification about supported platforms.
Swapped order of 2.6.1 and 2.6.2 sections.
Minor rewordings. Other markdown linting fixes.
=> Documentation fixes

doc/security_server_sidecar_security_guide.md
Security Server Sidecar security documentation.
=> XRDDEV-1312

doc/files/load_balancer_setup.yaml, doc/kubernetes_security_guide.md, doc/kubernetes_security_server_sidecar_user_guide.md, doc/security_server_sidecar_security_guide.md, doc/security_server_sidecar_user_guide.md, setup_security_server_sidecar.sh, sidecar/Dockerfile, sidecar/docker-build.sh, sidecar/fi/Dockerfile, sidecar/files/_entrypoint_common.sh, sidecar/files/slim-ss-xroad.conf, sidecar/files/ss-xroad.conf, sidecar/kubernetes/security-server-sidecar-local.yaml, sidecar/kubernetes/security-server-sidecar-slim.yaml, sidecar/kubernetes/security-server-sidecar.yaml, sidecar/kubernetesBalancer/fi/primary/Dockerfile, sidecar/kubernetesBalancer/fi/secondary/Dockerfile, sidecar/kubernetesBalancer/primary/Dockerfile, sidecar/kubernetesBalancer/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/fi/primary/Dockerfile, sidecar/kubernetesBalancer/slim/fi/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/primary/Dockerfile, sidecar/kubernetesBalancer/slim/secondary/Dockerfile, sidecar/slim/Dockerfile, sidecar/slim/fi/Dockerfile
- Updated X-Road version 6.25.0 to 6.26.0.
- Updated Ubuntu base image to 20.4.
- Updated PostgreSQL packages version to 12.
=> XRDDEV-1632

doc/security_server_sidecar_user_guide.md
Added 6.25.0 to 6.26.0 upgrade steps
=> XRDDEV-1632-1

sidecar/docker-build.sh, sidecar/files/balancer-primary-entrypoint.sh, sidecar/is/Dockerfile, sidecar/kubernetesBalancer/fi/secondary/Dockerfile, sidecar/kubernetesBalancer/is/primary/Dockerfile, sidecar/kubernetesBalancer/is/secondary/Dockerfile, sidecar/kubernetesBalancer/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/fi/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/is/primary/Dockerfile, sidecar/kubernetesBalancer/slim/is/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/secondary/Dockerfile, sidecar/slim/is/Dockerfile
Modify the build script to additionally build `is` images
=> XRDDEV-1831 Add Dockerfiles for Iceland configuration

sidecar/files/primary-ss-xroad.conf, sidecar/files/secondary-ss-xroad.conf, sidecar/files/ss-xroad.conf
https://jira.niis.org/browse/XRDDEV-1816
add xroad-addon-messagelog service to non-slim container types
replaces https://github.com/nordic-institute/X-Road-Security-Server-sidecar/pull/74
=> XRDDEV-1816 add xroad-addon-messagelog (rebased)

sidecar/Dockerfile, sidecar/Dockerfile-variant, sidecar/kubernetes/security-server-sidecar-slim.yaml, sidecar/kubernetes/security-server-sidecar.yaml, sidecar/kubernetesBalancer/primary/Dockerfile, sidecar/kubernetesBalancer/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/primary/Dockerfile, sidecar/kubernetesBalancer/slim/secondary/Dockerfile, sidecar/slim/Dockerfile
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2115
=> Pump version to 7.1.1

doc/kubernetes_security_guide.md, doc/kubernetes_security_server_sidecar_user_guide.md, doc/security_server_sidecar_security_guide.md, doc/security_server_sidecar_user_guide.md
https://nordic-institute.atlassian.net/browse/XRDDEV-2114
Restoration script fix in https://github.com/nordic-institute/X-Road/pull/1388
=> XRDDEV-2114: Updating documentation regarding upgrade process

sidecar/files/slim-ss-xroad.conf, sidecar/files/ss-xroad.conf
https://nordic-institute.atlassian.net/browse/XRDDEV-2161
=> XRDDEV-2161: Start cron service on startup

sidecar/docker-build.sh, sidecar/slim/Dockerfile
Fix https://security.snyk.io/vuln/SNYK-UBUNTU2004-PCRE2-2810784
=> XRDDEV-2236 update pcre2-utils

sidecar/Dockerfile, sidecar/Dockerfile-variant, sidecar/kubernetes/security-server-sidecar-slim.yaml, sidecar/kubernetes/security-server-sidecar.yaml, sidecar/kubernetesBalancer/primary/Dockerfile, sidecar/kubernetesBalancer/secondary/Dockerfile, sidecar/kubernetesBalancer/slim/primary/Dockerfile, sidecar/kubernetesBalancer/slim/secondary/Dockerfile, sidecar/slim/Dockerfile
=> chore: 7.3.0 Release
